# Generated by Django 5.2.4 on 2025-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('tech_stack', models.CharField(max_length=200)),
                ('demo_link', models.URLField(blank=True)),
                ('source_code', models.URLField(blank=True)),
            ],
        ),
    ]
